# Generated by Django 5.0.1 on 2024-01-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='starting_token',
            field=models.CharField(choices=[('X', 'Cross'), ('O', 'Circle')], default='X', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='turn',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
