# Generated by Django 5.0.1 on 2024-01-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_game_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
