version: '3'

services:

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
  web:
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
